# curl -X GET http://localhost:8080/actuator/health
GET http://localhost:8080/actuator/health

###

# curl -X GET http://localhost:8080/actuator/profile-db-details
GET http://localhost:8080/actuator/profile-db-details

###
